[project]
authors = ["mmyrte <24587121+mmyrte@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pcr-globwb"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
numpy = "*"
pip = "*"
python-dateutil = "*"
six = ">=1.17.0,<2"
zlib = "*"
pcraster = ">=4.4.0"
netcdf4 = ">=1.5.3"
cdo = "*"
nco = "*"
ncview = "*"
